apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{.Release.Name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-{{.Release.Name}}
    spec:
      containers:
      - name: {{ .Values.name }}-{{.Release.Name}}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: {{ .Values.image.type}}
  ports:
  - protocol: TCP
    port: 80
    name: http
  - protocol: TCP
    port: 443
    name: https
  selector:
    app: {{ .Values.name }}-{{.Release.Name}}